# Generated by Django 4.2 on 2023-04-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(blank=True, max_length=255, null=True)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("lead_by", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "employee",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("warehouse_id", models.IntegerField(blank=True, null=True)),
                ("date_of_stock", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "item",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.IntegerField(blank=True, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "warehouse",
                "managed": False,
            },
        ),
    ]
