# Generated by Django 4.2 on 2023-04-04 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stock", "0004_user_delete_comments_alter_post_post_delete_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="post",
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
