# Generated by Django 4.2 on 2023-04-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0005_remove_post_post_post_author_post_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
