# Generated by Django 4.2 on 2023-04-04 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0009_post_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stock.comment",
            ),
        ),
    ]
