# Generated by Django 4.2 on 2023-04-26 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0017_alter_item_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="warehouse_id",
        ),
        migrations.AddField(
            model_name="item",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="stock.warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="state",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
