# Generated by Django 4.2 on 2023-04-26 21:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0018_remove_item_warehouse_id_item_warehouse_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"managed": False},
        ),
    ]
