# Generated by Django 4.2 on 2023-04-26 21:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0019_alter_item_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"managed": False, "ordering": ["date_of_stock"]},
        ),
    ]
